
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-example}
    networks:
      - app-network
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: nextjs-app
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    environment:
      MONGODB_URI: mongodb://${MONGO_USERNAME:-user}:${MONGO_PASSWORD:-password}@mongodb:27017/${MONGO_DB:-mydb}?authSource=admin
      # Add any other environment variables your Next.js app needs here
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge